### ISSUE TITLE
"wrong ELF class: ELFCLASS64" on a RaspberryPi 3b

### ISSUE THREAD

**Issue by mariocarro** [asfernandes/node-firebird-drivers#146]
yarn run v1.22.19
warning package.json: No license field
$ yarn run compile && node lib/
warning package.json: No license field
$ shx rm -rf lib/ && tsc
/usr/src/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /usr/src/app/node_modules/node-firebird-native-api/build/Release/addon.node: wrong ELF class: ELFCLASS64
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/src/app/node_modules/node-firebird-native-api/dist/lib/index.js:31:35)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.11.1
error Command failed with exit code 1.

**Comment by mariocarro** [comment]
Not really a bug in this package...
