### ISSUE TITLE
Sources doesn't compile under newest Node 12.1

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-drivers#22]
I have got following error:

```
c:\golden\ns\gdmn\node_modules\node-firebird-native-api\src\native\./cloop-gen.h(5527): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments (compiling source file ..\src\native\fb-native.cpp) [C:\Golden\NS\gdmn\node_modules\node-firebird-native-api\build\addon.vcxproj]
c:\golden\ns\gdmn\node_modules\node-firebird-native-api\src\native\./cloop-gen.h(5527): fatal error C1003: error count exceeds 100; stopping compilation (compiling source file ..\src\native\fb-native.cpp) [C:\Golden\NS\gdmn\node_modules\node-firebird-native-api\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Golden\NS\gdmn\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Golden\\NS\\gdmn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Golden\NS\gdmn\node_modules\node-firebird-native-api
```

**Comment by asfernandes** [comment]
Cannot reproduce in my machine and travis https://travis-ci.com/asfernandes/node-firebird-drivers/jobs/197634038

**Comment by asfernandes** [comment]
Now I see that v0 is not working.

**Comment by asfernandes** [comment]
I'm not sure I'll fix v0 for node 12. v1 will be the future.

**Comment by gsbelarus** [comment]
Have you recompiled v1-beta2 with node 12.1 under Windows? Because I have strange errors in node-gyp and the code doesn't compile.

**Comment by asfernandes** [comment]
Should be fixed in beta 3 (already released) as well as the problem with VS 2017/2019 build. Please test it.

**Comment by gsbelarus** [comment]
Ok. Thank you a lot. I will test it in a few days.
